### ISSUE TITLE
I can't get right clustering,here is my code

### ISSUE THREAD

**Issue by guangminglftg** [stephenbeckr/SSC#4]
rng('default') % For reproducibility

% Parameters for data generation
N = 300;  % Size of each cluster
r1 = 2;   % Radius of first circle
r2 = 4;   % Radius of second circle
theta = linspace(0,2*pi,N)';

X1 = r1*[cos(theta),sin(theta)]+ rand(N,1); 
X2 = r2*[cos(theta),sin(theta)]+ rand(N,1);
X = [X1;X2]; % Noisy 2-D circular data set
C=SSC_viaADMM(X.')
S=abs(C)+abs(C.')
idx=spectralcluster(S,2,"Distance","precomputed")
gscatter(X(:,1),X(:,2),idx)
############ and it looks like :
![image](https://user-images.githubusercontent.com/75927302/232025720-e86ead2f-e220-4e18-ae21-b217d8c492ba.png)

**Comment by stephenbeckr** [comment]
I'm not sure this is a code issue, but rather it might just be the case that it's the wrong tool for that type of clustering.  SSC assumes that the clusters are subspaces, but (unless you lift your data to a higher dimension with a kernel) that dataset does not look like it has subspaces.  SSC is doing it's best, and you can see that it has implicitly made two lines (subspaces) and each point is assigned a cluster based on which line it is closest to.

**Comment by guangminglftg** [comment]
l1=2*rand(N,1)
l2=2*rand(N,1)
X1=[l1,0.66*l1+1]
X2=[l2,-1.48*l2+2]

X=[X1;X2]
X=X.'
#scatter(X(1,:),X(2,:),'.') plot it if necessary, as it is two lines

C=SSC_viaADMM(X)
C=normc(C)
S=abs(C)+abs(C.')
idx=spectralcluster(S,2,"Distance","precomputed")
gscatter(X(1,:),X(2,:),idx)
# and the result goes like -->
![image](https://user-images.githubusercontent.com/75927302/232537759-b3de9d1d-a160-4199-8ac4-dd1f8f8735c3.png)

**Comment by guangminglftg** [comment]
> I'm not sure this is a code issue, but rather it might just be the case that it's the wrong tool for that type of clustering. SSC assumes that the clusters are subspaces, but (unless you lift your data to a higher dimension with a kernel) that dataset does not look like it has subspaces. SSC is doing it's best, and you can see that it has implicitly made two lines (subspaces) and each point is assigned a cluster based on which line it is closest to.

thankyou for explaination, but I still have some problems

**Comment by stephenbeckr** [comment]
In your example, you have two affine spaces, not two linear subspaces.  If you want to do affine space clustering, set the `'affine'` variable to `true` in the `SSC_viaADMM` code

**Comment by guangminglftg** [comment]
N=160
l1=linspace(0,2,N).'
l2=l1
X1=[l1,0.66*l1+1]
X2=[l2,-1.48*l2+2]

X=[X1;X2]
X=X.'
C=SSC_viaADMM(X)
C=normc(C)
S=abs(C)+abs(C.')
idx=spectralcluster(S,2,"Distance","precomputed")
gscatter(X(1,:),X(2,:),idx)
# and it goes like ->
![untitled](https://user-images.githubusercontent.com/75927302/232541702-b057d661-4c23-4d21-895d-4186aad660d2.jpg)

**Comment by guangminglftg** [comment]
while i think it maybe because of Affine space instead of subspace

**Comment by guangminglftg** [comment]
> 

thank you !

**Comment by stephenbeckr** [comment]
You're welcome. I'm going to close out this issue
